sudo: required
dist: trusty
language: node_js
node_js:
  - "8.9"
python:
  - "3.6"
services:
- docker
before_install:
- npm install -g npm@^5.x
- npm install -g node-gyp
- npm install -g snyk
install:
- npm install
script:
- npm run test
- npm run codacy
cache:
  directories:
  - node_modules
notifications:
  email:
    on_failure: change
    on_success: change
before_deploy:
- sudo apt-get install -y python3.4
- sudo apt-get install --upgrade -y python-pip
- chmod +x ./deploy.sh
deploy:
- provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: deploy-test