language: node_js
dist: trusty
sudo: required
node_js:
- lts/*
before_install:
- npm install -g snyk
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
- npm run test
- npm run codacy
cache:
  directories:
  - node_modules
notifications:
  email:
    on_failure: change
    on_success: change