sudo: required
dist: trusty
language: node_js
node_js:
    - "8.9.4"
language: node_js
before_install:
- npm install -g snyk
script:
- npm run test
- npm run codacy
cache:
  directories:
  - node_modules
notifications:
  email:
    on_failure: change
    on_success: change